// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/students": {
    params: {};
  };
  "/students/:id/details": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/students" | "/students/:id/details";
  };
  "pages/index.tsx": {
    id: "pages/index";
    page: "/";
  };
  "pages/students/index.tsx": {
    id: "pages/students/index";
    page: "/students";
  };
  "pages/students/detail.tsx": {
    id: "pages/students/detail";
    page: "/students/:id/details";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "pages/index": typeof import("./app/pages/index.tsx");
  "pages/students/index": typeof import("./app/pages/students/index.tsx");
  "pages/students/detail": typeof import("./app/pages/students/detail.tsx");
};